version: '3.8'

services:
  google-adx-optimization:
    build:
      context: .
      dockerfile: Dockerfile.optimized
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=1024
    volumes:
      - ./uploads:/app/uploads
      - ./results:/app/results
    restart: unless-stopped
    # 1C2G资源限制
    deploy:
      resources:
        limits:
          memory: 1.5G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.8'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  uploads:
  results: